=== jondos/MixConfig/MixConfiguration.dtd
<!ELEMENT MixConfiguration (General,Network,Certificates,Description)>
<!ATTLIST MixConfiguration version CDATA #FIXED "0.1">

<!ELEMENT General (MixID,MixType,MixName,CascadeName?,Daemon,UserID?,NrOfFileDescriptors?,Logging?)>
    <!ELEMENT MixID (#PCDATA)>
    <!ELEMENT MixType (#PCDATA)>
    <!ELEMENT MixName (#PCDATA)>
    <!ELEMENT CascadeName (#PCDATA)>
    <!ELEMENT Daemon (#PCDATA)>
    <!ELEMENT UserID (#PCDATA)>
    <!ELEMENT NrOfFileDescriptors (#PCDATA)>
    <!ELEMENT Logging (File|SysLog|Console)>
	<!ELEMENT File (#PCDATA)>
	    <!ATTLIST File compressed (True|False) #IMPLIED>
	<!ELEMENT SysLog (#PCDATA)>
	<!ELEMENT Console (#PCDATA)>

<!ELEMENT Network (ListenerInterfaces, (NextMix|Proxies), InfoService)>
    <!ELEMENT ListenerInterfaces (ListenerInterface+)>
	<!ELEMENT ListenerInterface (NetworkProtocol,((Host,IP?,Port)|File))>
    <!ELEMENT NextMix (NetworkProtocol,((Host,IP?,Port)|File))>
    <!ELEMENT Proxies (Proxy+)>
	<!ELEMENT Proxy (ProxyType, NetworkProtocol,((Host,IP?,Port)|File))>
	    <!ELEMENT ProxyType (#PCDATA)>
	    <!ELEMENT NetworkProtocol (#PCDATA)>
	    <!ELEMENT Host (#PCDATA)>
	    <!ELEMENT IP (#PCDATA)>
	    <!ELEMENT Port (#PCDATA)>
    <!ELEMENT InfoService (Host, IP?, Port)>

<!ELEMENT Certificates (OwnCertificate, PrevMixCertificate?, NextMixCertificate?)>
    <!ELEMENT OwnCertificate (X509PKCS12, X509Certificate)>
	<!ELEMENT X509PKCS12 (#PCDATA)>
	    <!ATTLIST X509PKCS12 xml:space (preserve) #IMPLIED>
	<!ELEMENT X509Certificate (#PCDATA)>
	    <!ATTLIST X509Certificate xml:space (preserve) #IMPLIED>
    <!ELEMENT PrevMixCertificate (X509Certificate)>
    <!ELEMENT NextMixCertificate (X509Certificate)>

<!ELEMENT Description (Location)>
    <!ELEMENT Location (City, State?, Country, Position)>
	<!ELEMENT City (#PCDATA)>
	<!ELEMENT Country (#PCDATA)>
	<!ELEMENT State (#PCDATA)>
	<!ELEMENT Position (Geo)>
	    <!ELEMENT Geo (Longitude, Latitude)>
		<!ELEMENT Longitude (#PCDATA)>
		<!ELEMENT Latitude (#PCDATA)>

=== jondos/MixConfig/MixConfig/trunk/MixConfiguration.xml
<?xml version="1.0" ?>
<!DOCTYPE MixConfiguration SYSTEM "MixConfiguration.dtd">

<!-- XML File for Mix Configuration -->

<MixConfiguration version="0.2">  <!-- Root-Element -->
<!-- Changes in Version 0.2:
		- added attr 'hidden' and 'virtual' to ListenerInterface
-->
<General>
	<MixID> <!-- Each Mix gets an unique ID, ether chosen by the user or generate
					Rules:
						MixID::='m' (Letter|Digits|'.'|'_'|'-'){4:n}
						Letter::='A'..'Z'|'a'..'z'
						Digits::='0'..'9'
	-->
	</MixID>
	<MixType> <!--- One of: FirstMix | MiddleMix | LastMix --> </MixType>
	<MixName> <!-- human readble String which shortly describes the Mix --> </MixName>
	<CascadeName>
	<!-- human readable String which shortly describes the whole Mix-Cascade
	Only available if MixType==FirstMix
	--></CascadeName>
	<Daemon> <!-- Should the mix run in the background as daemon ? Values: True | False --> </Daemon>
	<UserID> <!-- The userid the Mix-process should use than running --> </UserID>
	<NrOfFileDescriptors> <!-- max Number of file descriptors the mix should use --> </NrOfFileDescriptors>

	<Logging>
		<!-- Information of how to log some events -->
		<!-- Only one of the following three is possible -->
		<File compressed="True|False"><!--The file to which the log data should be writen--></File>
		<SysLog>  <!-- Values: True | False --> </SysLog>
		<Console> <!-- Values: True | False, must be False, if Daemon=True --> </Console>
	</Logging>
</General>

<Network>
	<ListenerInterfaces>
		<!-- Describes on which interfaces (IP-Addresses etc.) the Mix should listen for incoming connections-->

		<ListenerInterface hidden="True|False" virtual="True|False">
			<!-- Describes one Listener, only first mixes could have more than one Listener-->
			<!-- A Listener uses either TCP/IP or Unix Domain Sockets -->
			<!-- If a ListenerInterface is "hidden" this means, that information about this interface
					is not propagate to the InfoService -->
			<!-- If a ListenerInterface is "virtual" this means, that the Mix will not really bind and listen
					on this interface (but information about this interface is transfered to the InfoService)
			<!-- Note: "hidden" and "virtual" are usefully for instance if the mix is behind a NAT-Gateway-->

			<!-- NEW: Type of Listener Interface-->
			<NetworkProtocol><!-- Possible Values: RAW/TCP, RAW/UNIX, SSL/TCP, SSL/UNIX --></NetworkProtocol>


			<!-- For TCP/IP (if type= */TCP) -->
			<Host> <!-- Hostname or IP on which to listen --> </Host>
			<IP> <!-- Optional, if given it must be the IP for <HOST> --> </IP>
			<Port> <!-- Port on which to listen--></Port>

			<!-- For Unix Domain Sockets (if type= */UNIX)-->
			<File> <!-- Filename, which should be used for Unix Domain Sockets--> </File>

	 </ListenerInterface>

	</ListenerInterfaces>

	<NextMix>
	<!-- Describes how to connect to the next mix,
			 only usefull for First- or MiddleMix -->
			 <NetworkProtocol>  !-- Possible Values: RAW/TCP, RAW/UNIX, SSL/TCP, SSL/UNIX --></NetworkProtocol>
			 <Host> hostname or ip of next Mix </Host>
			 <IP> <!-- Optional, if given it must be the IP for <HOST> --> </IP>
			 <Port> port of next mix </Port>

			 <File> <!-- Filename, if unix Domain Sockets should be used --> </File>

	</NextMix>

	<Proxies>
	<!-- Describes which proxies are available for the last mix and how to reach them,
			only useful for the last mix -->

			<Proxy>
				<!-- Describes one single proxy -->
					<ProxyType> <!-- Type of Proxy, one of: HTTP|SOCKS --></ProxyType>
					<NetworkProtocol> !-- Network protocol -- Possible Values: RAW/TCP, RAW/UNIX, SSL/TCP, SSL/UNIX --></NetworkProtocol>
					<!-- How to reach this proxy ?-->
					<Host> </Host>
					<IP> <!-- Optional, if given it must be the IP for <HOST> --> </IP>
					<Port> </Port>
					<File> </File>

			</Proxy>

	</Proxies>
	<InfoService>
		<!-- Describes how to connect to the InfoService -->

			 <Host> hostname or ip of the InfoService </Host>
			 <IP> <!-- Optional, if given it must be the IP for <HOST> --> </IP>
			 <Port> port of the InfoService </Port>

	</InfoService>
</Network>

<Certificates>

	<OwnCertificate>
		<X509PKCS12>
			<!-- Base64 encoded version of the DER encoded version of a PKCS#12 structure which includes the private key and X.509 Certificate -->
		</X509PKCS12>

		<X509Certificate>
			<!-- Base64 encoded version of the DER encoded version of the X.509 Certificate -->
			<!-- this is the public test certificate, which belongs to the certificate above -->
		</X509Certificate>
	</OwnCertificate>

	<PrevMixCertificate>
	<!-- X.509 Public Key Test Certificate of the key from the previous mix -->
		<X509Certificate>
			<!-- Base64 encoded version of the DER encoded version of the X.509 Certificate -->
		</X509Certificate>
	</PrevMixCertificate>

	<NextMixCertificate>
	<!-- X.509 Public Key Test Certificate of the key from the next mix -->
		<X509Certificate>
			<!-- Base64 encoded version of the DER encoded version of the X.509 Certificate -->
		</X509Certificate>
	</NextMixCertificate>

</Certificates>

<Description>
	<Location> <!-- Describes the location of the mix server -->
		<City>    </City>
		<Country> </Country>
		<State> <!-- optional --> </State>

		<Position>
			<Geo> <!--The geographical position of the mix server -->
				<Longitude></Longitude>
				<Latitude></Latitude>
			</Geo>
		</Position>

	</Location>

	<Operator> <!-- who is operating this mix? -->
		<Organisation> <!-- The name of the operating organisation or a person's name for private operators --> </Organisation>
		<URL> <!-- a url that leads to more information on the operator, including contact information --> </URL>
	</Operator>

</Description>


</MixConfiguration>
